# Generated by Django 6.0.1 on 2026-01-31 02:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_businessprofile_onboarding_completed_and_more'),
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='status',
        ),
        migrations.AddField(
            model_name='invoice',
            name='owner',
            field=models.ForeignKey(default=111111, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='accounts.personalprofile'),
            preserve_default=False,
        ),
    ]
