# Generated by Django 6.0.1 on 2026-01-31 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='personalprofile',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
